spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/consulteme
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: demo
      username: admin
      password: password
      port: 27017
      host: localhost
      authentication-database: admin
jwt:
  secret: a73b5898-834f-4b95-88b0-0cc1e0ded7fc
